apiVersion: v1
data:
  token: NTk3NDExMjYzOTpBQUZQSFp6MlNZM2xkcmE4T3phUDR3em4zM0tSZHo4bWFhdw==
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    version: {{ .Chart.AppVersion }}
