# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
autoscaling:
  enabled: false
ingress:
  enabled: false
image:
  registry: "ghcr.io"
  repository: "nickp007"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.6-d8720a1"
  os: linux
  arch: amd64
secret:
  name: kbot-secret
  tokenKey: token
  tokenName: TELE_TOKEN
  tokenValue:
service:
  port: 80
securityContext:
  privileged: true
